# Generated by Django 5.1.2 on 2024-10-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_units', models.IntegerField()),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('last_donation', models.DateField()),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('quantity_needed', models.IntegerField()),
                ('request_date', models.DateField()),
                ('blood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodtype')),
            ],
        ),
    ]
